apiVersion: apps/v1
kind: Deployment
metadata:
  name: permission-manager
  labels:
    app: permission-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: permission-manager
  template:
    metadata:
      labels:
        app: permission-manager
    spec:
      serviceAccountName: permission-manager
      containers:
        - name: permission-manager
          image: quay.io/sighup/permission-manager:v1.6.0
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - secretRef:
                name: permission-manager
          resources:
{{ toYaml .Values.resources | indent 12 }}