apiVersion: v1
kind: Service
metadata:
  name: {{ include "haproxy.fullname" . }}
  labels:
    {{- include "haproxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    - port: 8899
      targetPort: 8899
      protocol: TCP
      name: web
  selector:
    {{- include "haproxy.selectorLabels" . | nindent 4 }}
