apiVersion: v1
name: haproxy
version: 0.0.1
appVersion: 2.2.3
description: Fast, reliable, scalable, and easy to use proxy
icon: https://res-3.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco/yroykjzjfi8lmeam58xp
keywords:
- haproxy
- proxy
maintainers:
  - email: kfirfer@gmail.com
    name: kfir

