{{- if .Values.podSecurityPolicy.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "onlyoffice.fullname" . }}-clusterrole
rules:
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - {{ include "onlyoffice.fullname" . }}-psp
    verbs:
      - use
{{- end }}
