apiVersion: v2
name: mysql-check
description: A Helm chart for Kubernetes
icon: https://www.mysql.com/common/logos/logo-mysql-170x115.png
type: application
version: 0.0.1
appVersion: 10.4.13
maintainers:
  - email: kfirfer@gmail.com
    name: kfir

