apiVersion: v1
kind: Secret
metadata:
  name: permission-manager
type: Opaque
stringData:
  PORT: "{{ .Values.service.port }}"
  CLUSTER_NAME: "{{ .Values.clusterName }}"
  CONTROL_PLANE_ADDRESS: "{{ .Values.controlPlaneAddress }}"
  BASIC_AUTH_PASSWORD: "{{ .Values.basicAuthPassword }}"
